"""Tests for tower estimation and path-loss regression kriging."""

from __future__ import annotations

import numpy as np
import pytest

from mukoo_model.data import PointCloud
from mukoo_model.regression import PathLossKrigingModel
from mukoo_model.towers import estimate_towers, nearest_tower_distance


def test_estimate_towers_centroid_near_strongest_readings():
    # One cell: samples on a line, power decaying away from x=1000. The
    # linear-power weighting should put the tower estimate near x=1000.
    rng = np.random.RandomState(0)
    x = np.linspace(0.0, 5000.0, 60)
    y = np.zeros_like(x)
    rsrp = -70.0 - 25.0 * np.log10(np.maximum(np.abs(x - 1000.0), 50.0) / 50.0)
    cell = np.array(["cellA"] * 60, dtype=object)
    towers = estimate_towers(x, y, rsrp + rng.randn(60) * 0.5, cell, min_samples=20)
    assert towers.shape == (1, 2)
    assert abs(towers[0, 0] - 1000.0) < 400.0


def test_estimate_towers_skips_thin_cells_and_blank_labels():
    x = np.arange(30, dtype=np.float64)
    y = np.zeros(30)
    rsrp = np.full(30, -90.0)
    cell = np.array(["a"] * 10 + [""] * 20, dtype=object)  # a: too thin; "": blank
    towers = estimate_towers(x, y, rsrp, cell, min_samples=20)
    assert towers.shape == (0, 2)


def test_nearest_tower_distance_clips_minimum():
    towers = np.array([[0.0, 0.0]])
    d = nearest_tower_distance(np.array([0.0, 1000.0]), np.array([0.0, 0.0]), towers)
    assert d[0] == 30.0  # clipped, never 0
    assert np.isclose(d[1], 1000.0)


def _pathloss_cloud(n=400, seed=0):
    """Synthetic field that IS a path-loss law: two towers, log-distance decay."""
    rng = np.random.RandomState(seed)
    x = rng.rand(n) * 10000.0
    y = rng.rand(n) * 10000.0
    towers = np.array([[2000.0, 2000.0], [8000.0, 7000.0]])
    d = np.sqrt(
        ((x[:, None] - towers[None, :, 0]) ** 2)
        + ((y[:, None] - towers[None, :, 1]) ** 2)
    ).min(axis=1)
    d = np.clip(d, 30.0, None)
    z = -60.0 - 20.0 * np.log10(d) + rng.randn(n) * 1.0
    # cell label = nearest tower, so tower estimation has something to find
    nearest = np.argmin(
        np.sqrt(
            ((x[:, None] - towers[None, :, 0]) ** 2)
            + ((y[:, None] - towers[None, :, 1]) ** 2)
        ),
        axis=1,
    )
    cell = np.array([f"cell-{i}" for i in nearest], dtype=object)
    return PointCloud(
        lon=x / 1e5 - 81.8,
        lat=y / 1e5 + 32.35,
        x=x,
        y=y,
        values=z,
        crs_epsg=32617,
        metric="rsrp",
        n_raw=n,
        cell=cell,
    )


def test_pathloss_model_recovers_negative_slope():
    cloud = _pathloss_cloud()
    model = PathLossKrigingModel(nlags=10).fit(cloud)
    params = model.variogram_params
    assert params["trend"] == "pathloss"
    # true slope is -20 dB/decade; estimation from bootstrapped towers is
    # rough but must be clearly negative and in a physical ballpark.
    assert -35.0 < params["trend_slope_per_log10m"] < -8.0


def test_pathloss_predicts_and_grids(linear_cloud):
    cloud = _pathloss_cloud()
    model = PathLossKrigingModel(nlags=10).fit(cloud)
    mean, var = model.predict_points(np.array([5000.0]), np.array([5000.0]))
    assert np.isfinite(mean[0]) and var[0] >= 0
    from mukoo_model.kriging import make_grid

    surface = model.predict_grid(make_grid(cloud, cell_m=1000.0))
    assert surface.variogram_model.startswith("pathloss+")
    assert surface.mean.shape == surface.grid.shape
    assert np.all(np.isfinite(surface.mean))


def test_pathloss_requires_cell_labels():
    cloud = _pathloss_cloud()
    bare = PointCloud(
        lon=cloud.lon,
        lat=cloud.lat,
        x=cloud.x,
        y=cloud.y,
        values=cloud.values,
        crs_epsg=cloud.crs_epsg,
        metric="rsrp",
        n_raw=cloud.n_raw,
    )
    with pytest.raises(ValueError):
        PathLossKrigingModel(nlags=10).fit(bare)


def test_pathloss_cv_beats_ordinary_on_pathloss_field():
    # On a field generated BY a path-loss law, regression kriging must beat
    # ordinary kriging out-of-area (block CV), where the trend extrapolates
    # and pure interpolation cannot.
    from mukoo_model.crossval import block_cv
    from mukoo_model.kriging import OrdinaryKrigingModel

    cloud = _pathloss_cloud(n=500, seed=1)

    def pl_factory():
        return PathLossKrigingModel(nlags=10, cell=cloud.cell).bind_cloud(
            cloud.x, cloud.y
        )

    def ok_factory():
        return OrdinaryKrigingModel(nlags=10)

    pl = block_cv(cloud, model_factory=pl_factory, block_m=2500.0, seed=0)
    ok = block_cv(cloud, model_factory=ok_factory, block_m=2500.0, seed=0)
    assert pl.rmse < ok.rmse
